# specify dependencies for myblender.org operation (see also apt.txt
# for the full set)
channels:
    - conda-forge
dependencies:
    - fresnel
    - freud
    - hoomd
    - pyglet
    - pip
    - pip:
      - matplotlib
      - pythreejs
      - vispy
      - git+https://github.com/glotzerlab/plato#egg=plato-draw
      - pyriodic-aflow
      - pyside2
      - gtar
      - flowws
      - git+https://github.com/klarh/flowws-analysis
      - git+https://github.com/klarh/flowws-freud
      - git+https://github.com/klarh/hoomd_flowws
