# specify dependencies for myblender.org operation (see also apt.txt
# for the full set)
channels:
    - conda-forge
dependencies:
    - fresnel
    - freud
    - hoomd
    - pyglet
    - pip
    - pip:
      - matplotlib
      - pythreejs
      - vispy
      - plato-draw
      - pyriodic-aflow
      - pyside2
      - gtar
      - flowws
      - flowws-analysis
      - flowws-freud
      - flowws-unit-cell
      - hoomd_flowws
